### ISSUE TITLE
Big Divergence for Poland

### ISSUE THREAD

**Issue by Ellectronx** [RemiTheWarrior/epidemic-simulator#11]
Can you explain the divergence? Can it be fixed?
![Figure_1_Poland](https://user-images.githubusercontent.com/46204162/77399596-0ab93800-6daa-11ea-9f51-650ccddbfa01.png)

**Comment by RemDelaporteMathurin** [comment]
Hi, Poland is not the only country for which fitting is complicated. It's either because there's not enough points yet, or that the initial guess needs to be tweaked a little. You could try to tweak the `x_n` parameter as well

**Comment by RemDelaporteMathurin** [comment]
By tweaking the initial guess a little, I managed to get this fit.

Be aware though, that we don't have enough points yet in order to be accurate. 
![Figure_1](https://user-images.githubusercontent.com/40028739/77401759-c7f95f00-6dad-11ea-90c7-7fdb19b18b0a.png)
![Figure_2](https://user-images.githubusercontent.com/40028739/77401760-c92a8c00-6dad-11ea-99a5-e33d2f58152c.png)

**Comment by Ellectronx** [comment]
Hi, thank you for explanation. 
What value did you take for x_n in above diagrams?  
Can you explain default value x_n = 1e5 =100000. (comment says: initial healthy population - but why so small?)
Thanks in advance and good luck!

**Comment by RemDelaporteMathurin** [comment]
Ah yes, this is arbitrary really. Thing is most of these curves are  unfittable with the actual number of inhabitants for `x_n`. This means that we'll be able to fit the curve, and have an idea of when will the epidemic be over, but the contamination rate `K_c` will be physically meaningless.

If you have a better idea for improving this model I'm all ears 😃
