### ISSUE TITLE
Some Issues with the Numbers - Malaysia

### ISSUE THREAD

**Issue by inetkenya** [RemiTheWarrior/epidemic-simulator#16]
There seems to be an issue with Malaysia Number. Currently the stand @ above 2300 but from the chart, I see under 2000.

<img width="995" alt="Screenshot 2020-03-29 at 10 39 16 AM" src="https://user-images.githubusercontent.com/2420252/77838861-51dc6a00-71aa-11ea-9b79-a8338a6fdec3.png">

<img width="599" alt="Screenshot 2020-03-29 at 10 45 41 AM" src="https://user-images.githubusercontent.com/2420252/77838882-8cde9d80-71aa-11ea-9077-801ea275988d.png">

**Comment by RemDelaporteMathurin** [comment]
Hi @inetkenya, the plot you show is actually the **active** cases. The table here shows 2320 cases since the beginning of the outbreak (doesn't discriminate deaths or recovered people).

Active cases = Total cases (cumulative) - deaths - recovered

If you take a look a the table, it shows 1,973 active cases which is in good agreement with the graph.

**Comment by inetkenya** [comment]
Thanks for the clarification Bro.
